---
- name: Add parameter to the grub
  become: true
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(?!.* {{ item.regex }})(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 {{ item.context }}"'
    state: present
    backrefs: yes
  loop:
    - { regex: 'transparent_hugepage=never', context: 'transparent_hugepage=never' }
    - { regex: 'cgroup_enable=memory', context: 'cgroup_enable=memory' }
    - { regex: 'swapaccount=1', context: 'swapaccount=1' }
  register: grub

- name: Make grub
  become: true
  command: "update-grub"
  when: grub.changed
  register: updategrub

- name: Restart machine
  become: true
  shell: sleep 2 && systemctl --message="Ansible updates triggered" reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: updategrub.changed

- name: Wait for server to restart successfully
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    search_regex: "OpenSSH"
    port: 22
    timeout: 300
    connect_timeout: 50
    delay: 5
  delegate_to: localhost
  become: false