---
- name: Tune PAM limits
  become: true
  pam_limits:
    dest: "{{ pam_limit_file }}"
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items: "{{ pam_settings }}"
