---
- name: Tune sysctl
  become: true
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ sysctl_file }}"
    reload: yes
  with_items: "{{ sysctl_config }}"
